language: 'ru'
connection:
  timeout: 200
  ip_address: 192.168.150.196
  port_numb: '55555'
threshold: 3132
number_of_sectors: 6
calibration_coefficients:
  2400:
  - 0.96
  - 0.82
  - 0.97
  - 0.92
  - 0.93
  - 1
  5800:
  - 0.8
  - 0.77
  - 1
  - 0.75
  - 0.93
  - 0.73
peleng_coefficients:
  24:
    a: 60
    b: 1.2
  58:
    a: 30
    b: 0.7
view:
  theme: dark_yellow.xml
  language: Russian
  full_screen: false
log:
  viewed_messages: 30
debug:
  connection_type: Player
  player_record: mavic24_2kruga.txt
  warning_sound: alert.mp3
  levels_in_peleng: true
  average_levels_for_peleng: false
  average_spectrum: false
data_char:
  accumulated_values: 400
sensivity_coeff: 0.3
widgets:
  levelWidget: true
  fpvVideoWidget: false
  fpvScopeWidget: true
  recordCalibrationWidget: true
  settingsConfiguration: true
configuration:
  frequencies:
    DJI_Mavic2_2_4:
    - 100
    - 200
    - 300
    DJI_Mavic3_2_4:
    - 100
    - 200
    - 300
    Autel_2_4:
    - 100
    - 200
    - 300
    FPV_2_4:
    - 100
    - 200
    - 300
    Xiaomi_2_4:
    - 100
    - 200
    - 300
    DJI_MavicMini_2_4:
    - 100
    - 200
    - 300
    DJI_Mavic2_5_8:
    - 100
    - 200
    - 300
    DJI_Mavic3_5_8:
    - 100
    - 200
    - 300
    Autel_5_8:
    - 100
    - 200
    - 300
    FPV_5_8:
    - 100
    - 200
    - 300
    Xiaomi_5_8:
    - 100
    - 200
    - 300
    DJI_MavicMini_5_8:
    - 100
    - 200
    - 300
